# Generated by Django 5.2.3 on 2026-06-22 21:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Diseñador', 'Diseñador'), ('Desarrollador', 'Desarrollador'), ('Redactor', 'Redactor'), ('Productor', 'Productor'), ('Gerente Cultura', 'Gerente Cultura'), ('Gerente IC', 'Gerente IC'), ('Especialista', 'Especialista')], max_length=20, unique=True, verbose_name='Nombre del rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('perfil', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario IC', 'Usuario IC'), ('Heavy user', 'Heavy user'), ('Macro', 'Macro'), ('Usuario', 'Usuario')], default='Usuario', max_length=20, verbose_name='Perfil')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('es_focus', models.BooleanField(default=False, verbose_name='Es Focus')),
                ('areas_focus', models.CharField(blank=True, help_text='Áreas separadas por coma', max_length=200, verbose_name='Áreas Focus')),
                ('es_aprobador_default', models.BooleanField(default=False, verbose_name='Es aprobador por defecto')),
                ('puede_aprobar', models.BooleanField(default=False, verbose_name='Puede aprobar comunicaciones')),
                ('avatar_url', models.URLField(blank=True, help_text='URL externa o path relativo a static', verbose_name='URL del avatar')),
                ('memoria_habilitada', models.BooleanField(default=True, verbose_name='Memoria conversacional habilitada')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='core.role', verbose_name='Roles')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['perfil'], name='core_user_perfil_69a0d4_idx'), models.Index(fields=['es_focus'], name='core_user_es_focu_266d70_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
