# Generated by Django 5.2.15 on 2026-06-28 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('agent_execution', 'Ejecución de Agente'), ('agent_error', 'Error de Agente'), ('permission_blocked', 'Bloqueado por Permisos')], max_length=50, verbose_name='Tipo de evento')),
                ('agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agente')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('value', models.IntegerField(blank=True, help_text='Ej: execution_time_ms', null=True, verbose_name='Valor')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Evento de Métrica',
                'verbose_name_plural': 'Eventos de Métrica',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='core_metric_event_t_5279d0_idx'), models.Index(fields=['agent', 'timestamp'], name='core_metric_agent_fcda01_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=50, verbose_name='ID de conversación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('execution_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de ejecución (ms)')),
                ('user_message', models.TextField(verbose_name='Mensaje del usuario')),
                ('detected_intention', models.CharField(blank=True, max_length=100, verbose_name='Intención detectada')),
                ('selected_agent', models.CharField(max_length=100, verbose_name='Agente seleccionado')),
                ('selection_reason', models.TextField(blank=True, verbose_name='Motivo de selección')),
                ('permissions_applied', models.TextField(blank=True, verbose_name='Permisos aplicados')),
                ('system_decisions', models.JSONField(default=dict, verbose_name='Decisiones del sistema')),
                ('agent_response', models.TextField(blank=True, verbose_name='Respuesta del agente')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('final_state', models.CharField(choices=[('created', 'Creado'), ('running', 'Ejecutando'), ('needs_input', 'Necesita Input'), ('waiting_human', 'Esperando Humano'), ('pending_approval', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('blocked_by_permissions', 'Bloqueado por Permisos'), ('blocked_by_compliance', 'Bloqueado por Compliance'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='created', max_length=50, verbose_name='Estado final')),
                ('state_history', models.JSONField(default=list, verbose_name='Historial de estados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ejecución de Workflow',
                'verbose_name_plural': 'Ejecuciones de Workflow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_workfl_user_id_92fc51_idx'), models.Index(fields=['final_state'], name='core_workfl_final_s_03cb3b_idx'), models.Index(fields=['selected_agent'], name='core_workfl_selecte_3df925_idx'), models.Index(fields=['created_at'], name='core_workfl_created_65a66d_idx')],
            },
        ),
    ]
